id: I9BA5BB3A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T18:17:09+00:00'
last_modified: '2022-06-08T02:42:36.573148+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7042
  title: ཞིང་འབྲོག་ཉེར་སྤྱོད་ལག་རྩལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    43FD:
      image_group_id: I3CN7044
      title: ''
      total_pages: 452
      order: 1
      base_file: 43FD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
