id: P005385
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7042
  title: ཞིང་འབྲོག་ཉེར་སྤྱོད་ལག་རྩལ།
  author: ''
  volumes:
    ad5248aabe0e4cf6846573b67bd63706:
      image_group_id: I3CN7044
      title: ''
      volume_number: 1
      total_pages: 452
